include ../config.mk

NAME=r_main

OBJS=version.o
OBJS+=rax2.o
OBJS+=rasm2.o
OBJS+=ragg2.o
OBJS+=rarun2.o
OBJS+=rabin2.o
OBJS+=rafind2.o
OBJS+=r2agent.o
OBJS+=radiff2.o
OBJS+=radare2.o
OBJS+=rahash2.o

DEPS=r_util r_core r_syscall r_debug r_asm r_anal r_reg r_socket r_search r_flag r_cons r_io r_hash r_egg r_crypto r_fs r_config r_bin r_bp r_parse r_magic
# WITH_LIBS=0
# WITH_LIBR=1

include ../rules.mk
